<div id="attributeGrid">
<?php
    $this->widget('TradeGrid',array(
            'dataProvider'=>$model->search(),
            'filter'=>$model,
            'htmlOptions'=>array(
                    'class'=>'hor-scroll',
            ),
            'columns'=>array(
                    array(
                            'header'=>'ID',
                            'name'=>'messages_id',
                            'type'=>'raw',
						    'filter'=>false,
                    ),
                    array(
                            'header'=>'通知信息',
                            'name'=>'message_info',
                            'type'=>'raw',
						    'value'=>'$data->message_info',
							'filter'=>false,
                    ),
				   array(
                            'header'=>'通知等级',
                            'name'=>'messages_level',
                            'type'=>'raw',
					        'value'=>'$data->messages_level',
							'filter'=>array(1=>1,2=>2,3=>3),
                    ),
				    array(
                            'header'=>'通知时间',
                            'name'=>'messages_create_at',
                            'type'=>'raw',
					        'value'=>'$data->messages_create_at',
							'filter'=>false,
                    ),
            )
    ));
    ?>
</div>